# Generated by Django 2.2.1 on 2019-06-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_myuser_password_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='toDolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
