# Generated by Django 2.2 on 2019-04-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
